apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-cpu
  name: api-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-cpu
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/odfe-net: "true"
        io.kompose.service: api-cpu
    spec:
      containers:
        - image: phucnh22/mapintel-api-cpu:latest
          name: api-cpu
          resources:
            requests:
              memory: "750Mi"
              cpu: "500m"
            limits:
              memory: "1250Mi"
              cpu: "750m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /home/user/artifacts
              name: api-cpu-data
      restartPolicy: Always
      volumes:
        - name: api-cpu-data
          gcePersistentDisk:
            pdName: api-disk
            fsType: ext4

status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api-cpu
  name: api-cpu
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: api-cpu
